# Generated by Django 4.2.10 on 2024-02-18 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_reminder_delete_googlefitcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_goal', models.IntegerField()),
                ('calories_goal', models.IntegerField()),
                ('reminder_time', models.TimeField()),
                ('reminder_day', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
