# Generated by Django 4.2.10 on 2024-02-18 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_reminder_calories_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='calories_goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='step_goal',
            field=models.IntegerField(),
        ),
    ]
