# Generated by Django 4.2.10 on 2024-02-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_reminder_calories_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='latest_step_count',
            field=models.IntegerField(default=0),
        ),
    ]
