# Generated by Django 4.2.10 on 2024-02-23 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_reminder_latest_step_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='create_now',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
