# Generated by Django 4.2.10 on 2024-02-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_reminder_create_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='latest_step_count',
        ),
    ]
